### ISSUE TITLE
[Bug] [worker] Connections is not released after completing the SQL task

### ISSUE THREAD

**Issue by simon824** [apache/dolphinscheduler#11533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SQL type task and the data source is hive jdbc, the connection seems is not released after completing the SQL task, cause the number of connections always increasing.

The ds-worker at this point has no SQL tasks in progress, but there are still more than fifty connections
![image](https://user-images.githubusercontent.com/18065113/185283135-f18faa77-6dbd-4b68-b1e5-973b01ee7399.png)

### What you expected to happen

close the connection after completing the SQL task

### How to reproduce

1

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I meet the same problem of maintaining a connection to the database even when there was no task scheduled.

**Comment by ruanwenjun** [comment]
Is this happen in 3.0.0-release or just beta?

There is a same issue https://github.com/apache/dolphinscheduler/pull/11120, but has already been fixed at 3.0.0-release.

**Comment by stalary** [comment]
> Is this happen in 3.0.0-release or just beta?
> 
> There is a same issue #11120, but has already been fixed at 3.0.0-release.

3.0.0-release

**Comment by ruanwenjun** [comment]
> > Is this happen in 3.0.0-release or just beta?
> > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> 
> 3.0.0-release

3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.

**Comment by stalary** [comment]
> > > Is this happen in 3.0.0-release or just beta?
> > > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> > 
> > 
> > 3.0.0-release
> 
> 3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.

I locally standalone changed minimumIdle to 1 for all modules, but the total link is still 5.

**Comment by ruanwenjun** [comment]
> > > > Is this happen in 3.0.0-release or just beta?
> > > > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> > > 
> > > 
> > > 3.0.0-release
> > 
> > 
> > 3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.
> 
> I locally standalone changed minimumIdle to 1 for all modules, but the total link is still 5.

Could you please try to set the config `spring.datasource.minIdle=1` in `common.properties`.

**Comment by simon824** [comment]
> Could you please try to set the config `spring.datasource.minIdle=1` in `common.properties`.

@ruanwenjun What is the default value of `spring.datasource.minIdle`, I feel that there is no limit to the number of connections, and the jdbc connection on the worker side can easily grow to more than 100

**Comment by simon824** [comment]
Hi @stalary , how is this problem going, have you found the cause?

**Comment by stalary** [comment]
> Hi @stalary , how is this problem going, have you found the cause?

I haven't found the problem yet. I'll take a look at it when I'm free

**Comment by mongooooo** [comment]
+1 , I met the same problem, it is very destructive.

**Comment by chunhui5566** [comment]
I meet the same problem in 3.0.0-release also, i had to restart it when the jdbc connection increased to more than 100 now.

**Comment by stalary** [comment]
> I meet the same problem in 3.0.0-release also, i had to restart it when the jdbc connection increased to more than 100 now.

ok, let me check the problem.

**Comment by stalary** [comment]
> > > > > Is this happen in 3.0.0-release or just beta?
> > > > > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> > > > 
> > > > 
> > > > 3.0.0-release
> > > 
> > > 
> > > 3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.
> > 
> > 
> > I locally standalone changed minimumIdle to 1 for all modules, but the total link is still 5.
> 
> Could you please try to set the config `spring.datasource.minIdle=1` in `common.properties`.

You are right, the connection decrease when I config common.properties. @ruanwenjun  @chunhui5566 @mongooooo @simon824  But I think we should decrease default minIdle in code.

**Comment by chunhui5566** [comment]
> > > > > > Is this happen in 3.0.0-release or just beta?
> > > > > > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> > > > > 
> > > > > 
> > > > > 3.0.0-release
> > > > 
> > > > 
> > > > 3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.
> > > 
> > > 
> > > I locally standalone changed minimumIdle to 1 for all modules, but the total link is still 5.
> > 
> > 
> > Could you please try to set the config `spring.datasource.minIdle=1` in `common.properties`.
> 
> You are right, the connection decrease when I config common.properties. @ruanwenjun @chunhui5566 @mongooooo @simon824 But I think we should decrease default minIdle in code.

Thank you for you recheck and reply , i think the current problem is the connection not release, one day sooner or later it will still increased to more than 100 .  Befor V3.0.0-beta1  the datasource be put in map and there is no such problem.  now it in Guava Cache .  Could it be the problem?

**Comment by stalary** [comment]
> Thank you for you recheck and reply , i think the current problem is the connection not release, one day sooner or later it will still increased to more than 100 . Befor V3.0.0-beta1 the datasource be put in map and there is no such problem. now it in Guava Cache . Could it be the problem?

Yes, in 3.0-release it no problem~

**Comment by ruanwenjun** [comment]
> > > > > > > Is this happen in 3.0.0-release or just beta?
> > > > > > > There is a same issue #11120, but has already been fixed at 3.0.0-release.
> > > > > > 
> > > > > > 
> > > > > > 3.0.0-release
> > > > > 
> > > > > 
> > > > > 3.0.0release use DataSource in sql task, it will hold connection at default, you can reduce the [`minimumIdle`](https://github.com/brettwooldridge/HikariCP) to make the connection to be expire.
> > > > 
> > > > 
> > > > I locally standalone changed minimumIdle to 1 for all modules, but the total link is still 5.
> > > 
> > > 
> > > Could you please try to set the config `spring.datasource.minIdle=1` in `common.properties`.
> > 
> > 
> > You are right, the connection decrease when I config common.properties. @ruanwenjun @chunhui5566 @mongooooo @simon824 But I think we should decrease default minIdle in code.
> 
> Thank you for you recheck and reply , i think the current problem is the connection not release, one day sooner or later it will still increased to more than 100 . Befor V3.0.0-beta1 the datasource be put in map and there is no such problem. now it in Guava Cache . Could it be the problem?

Yes, in 3.0.0 release, we have fixed this bug.

**Comment by ruanwenjun** [comment]
Since this has already been fixed at 3.0.0 release, I will close this issue.

**Comment by simon824** [comment]
hi @stalary , set `export SPRING_DATASOURCE_MIN_IDLE=1`  in  `$DS_HOME/bin/env/dolphinscheduler_env.sh` ?

**Comment by simon824** [comment]
I had set the config `spring.datasource.minIdle=1` in `common.properties`, but after running for a few weeks I found that the problem still exists, the number of connections is still increasing.

**Comment by ruanwenjun** [comment]
> I had set the config `spring.datasource.minIdle=1` in `common.properties`, but after running for a few weeks I found that the problem still exists, the number of connections is still increasing.

You use 3.0.0-release or 3.0.0 beta?

**Comment by simon824** [comment]
> > I had set the config `spring.datasource.minIdle=1` in `common.properties`, but after running for a few weeks I found that the problem still exists, the number of connections is still increasing.
> 
> You use 3.0.0-release or 3.0.0 beta?

3.0.0-release

**Comment by ruanwenjun** [comment]
@simon824 @stalary Thanks for report this bug, I have submitted #12226 to fix this.
