### ISSUE TITLE
[Bug] [dolphinscheduler-worker] Unable to stop tasks in Seatunnel cluster

### ISSUE THREAD

**Issue by cqutwangyu** [apache/dolphinscheduler#15738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

我通过DS定时调度，使用Cluster模式启动Seatunnel任务。
然后通过DS页面中“工作流实例”->“操作”->“停止”按钮停止这个Seatunnel任务。

结果是，杀死了SeatunnelClient。
但事实上SeatunnelClient在Cluster模式下，只是讲任务提交到SeatunnelServer，真正执行任务在SeatunnelServer。
所以，杀死SeatunnelClient，只在Local模式下有用。
在Cluster模式下，需要调用Seatunnel提供的rest api -> "/hazelcast/rest/maps/stop-job"。

我本想自己实现在结束Seatunnel任务的同时调用这个接口，但我没有看到dolphinscheduler-task-seatunnel或dolphinscheduler-worker支持这样的扩展。

### What you expected to happen

pass

### How to reproduce

pass

### Anything else

pass

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JohnZp** [comment]
Bro, did you solve it? I also encountered the same problem;
In the latest version I am using now, temporarily suspending the task flow will cause the task flow to get stuck and stop the task. The task does not really stop;
My idea is to collect the jobid through logs, add a command line to the cancel method, and process the cancel method through SEATUNNLE_HOME/seatunnel.sh --cancel-job/--savepoint.

**Comment by cqutwangyu** [comment]
> Bro, did you solve it? I also encountered the same problem; In the latest version I am using now, temporarily suspending the task flow will cause the task flow to get stuck and stop the task. The task does not really stop; My idea is to collect the jobid through logs, add a command line to the cancel method, and process the cancel method through SEATUNNLE_HOME/seatunnel.sh --cancel-job/--savepoint.

Good idea, maybe you could try contributing source code.

**Comment by JohnZp** [comment]
> > Bro, did you solve it? I also encountered the same problem; In the latest version I am using now, temporarily suspending the task flow will cause the task flow to get stuck and stop the task. The task does not really stop; My idea is to collect the jobid through logs, add a command line to the cancel method, and process the cancel method through SEATUNNLE_HOME/seatunnel.sh --cancel-job/--savepoint.
> 
> Good idea, maybe you could try contributing source code.

I made the Seatunnel Stream task a separate plugin, similar to Flink Stream, doing separate tasks to start and stop and savepoint, but the customization is too strong, I don't know how to push it to the community

**Comment by davidzollo** [comment]
Some user told me that task can't stop and he provided the following picture, SeaTunnel version is 2.3.5 or 2.3.6 
![image](https://github.com/user-attachments/assets/878b7292-f304-4247-9d59-c75985594a31)

but we don‘t find unusual cause when checking the source code. Usually SeaTunnel process will be killed in cluster mode once you click stop button.
If any user meet the same problems, please provide some more messages such as SeaTunnel process screenshot in detail

By the way, if you have solved the problem, please also leave a message, thx

**Comment by ziya05** [comment]
> Some user told me that task can't stop and he provided the following picture, SeaTunnel version is 2.3.5 or 2.3.6 ![image](https://private-user-images.githubusercontent.com/15833811/356539866-878b7292-f304-4247-9d59-c75985594a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzg1NjMsIm5iZiI6MTcyNDczODI2MywicGF0aCI6Ii8xNTgzMzgxMS8zNTY1Mzk4NjYtODc4YjcyOTItZjMwNC00MjQ3LTlkNTktYzc1OTg1NTk0YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1NTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwOTRlOGJjZmMxZWM2Y2VmOWQ2YWJjODcwYTY1NTcyMTg3YWQ5NDJhZGRmMzBiYjdjNzhkZmI4NzZkMzhmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dP5cxpjUn_WpiT0gRypzBVquEIh68w3NJDI0R81rjRM)
> 
> but we don‘t find unusual cause when checking the source code. Usually SeaTunnel process will be killed in cluster mode once you click stop button. If any user meet the same problems, please provide some more messages such as SeaTunnel process screenshot in detail
> 
> By the way, if you have solved the problem, please also leave a message, thx

I found if I create a seatunnel task which read data from kafka and save data to database,  while set the job.mode to "STREAM", then stop the task after run it, the data will be update in database, and I can find the job from seatunnel REST Api.

By the way I hope dolphinscheduler will support seatunnel stream task, then I can manager the task in "realtime task".

**Comment by pzc-hhh** [comment]
> > > Bro, did you solve it? I also encountered the same problem; In the latest version I am using now, temporarily suspending the task flow will cause the task flow to get stuck and stop the task. The task does not really stop; My idea is to collect the jobid through logs, add a command line to the cancel method, and process the cancel method through SEATUNNLE_HOME/seatunnel.sh --cancel-job/--savepoint.
> > 
> > 
> > Good idea, maybe you could try contributing source code.
> 
> I made the Seatunnel Stream task a separate plugin, similar to Flink Stream, doing separate tasks to start and stop and savepoint, but the customization is too strong, I don't know how to push it to the community

Can you show me the code and how you modified the method for canceling tasks in Seatunnel? Thank you.

**Comment by 13813586515** [comment]
> Some user told me that task can't stop and he provided the following picture, SeaTunnel version is 2.3.5 or 2.3.6 ![image](https://private-user-images.githubusercontent.com/15833811/356539866-878b7292-f304-4247-9d59-c75985594a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Njk3NDEsIm5iZiI6MTczMjg2OTQ0MSwicGF0aCI6Ii8xNTgzMzgxMS8zNTY1Mzk4NjYtODc4YjcyOTItZjMwNC00MjQ3LTlkNTktYzc1OTg1NTk0YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA4MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzEwZWUwNjIxZDFkNjlmODlmMWNjZGE5NjlkNmNkMWFmY2I2OTdlNDkyOGQwM2U5MDI0NDVjMGRmNzI4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QeQpNa5zhu6sj86UyuU9JmaFlPnQsHAAUn1d_hdYMxE)
> 
> but we don‘t find unusual cause when checking the source code. Usually SeaTunnel process will be killed in cluster mode once you click stop button. If any user meet the same problems, please provide some more messages such as SeaTunnel process screenshot in detail
> 
> By the way, if you have solved the problem, please also leave a message, thx
did you solve it?

**Comment by pzc-hhh** [comment]
By modifying the source code, I have solved it




---Original---
From: ***@***.***&gt;
Date: Fri, Nov 29, 2024 16:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-worker] Unableto stop tasks in Seatunnel cluster (Issue #15738)




  
Some user told me that task can't stop and he provided the following picture, SeaTunnel version is 2.3.5 or 2.3.6 
 
but we don‘t find unusual cause when checking the source code. Usually SeaTunnel process will be killed in cluster mode once you click stop button. If any user meet the same problems, please provide some more messages such as SeaTunnel process screenshot in detail
 
By the way, if you have solved the problem, please also leave a message, thx
 did you solve it?

**Comment by 13813586515** [comment]
> By modifying the source code, I have solved it
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Nov 29, 2024 16:39 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-worker] Unableto stop tasks in Seatunnel cluster (Issue #15738) Some user told me that task can't stop and he provided the following picture, SeaTunnel version is 2.3.5 or 2.3.6 but we don‘t find unusual cause when checking the source code. Usually SeaTunnel process will be killed in cluster mode once you click stop button. If any user meet the same problems, please provide some more messages such as SeaTunnel process screenshot in detail By the way, if you have solved the problem, please also leave a message, thx did you solve it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

@davidzollo Has the official team fixed this bug yet

**Comment by 2062802390** [comment]
我在apache/dolphinscheduler-worker:3.1.9里面启动Seatunnel集群root@im-2:/opt/soft/seatunnel# nohup ./bin/seatunnel-cluster.sh 2>&1 &

**Comment by 2062802390** [comment]
我在apache/dolphinscheduler-worker:3.1.9里面启动Seatunnel集群root@im-2:/opt/soft/seatunnel# nohup ./bin/seatunnel-cluster.sh 2>&1 &
然后在dolphinscheduler运行Seatunnel任务，

![Image](https://github.com/user-attachments/assets/760f1786-0a53-49c1-b44e-4816a2b57f66)
在apache/dolphinscheduler-worker:3.1.9可以查看这个任务
Job ID              Job Name                   Job Status  Submit Time              Finished Time            
------------------  -------------------------  ----------  -----------------------  -----------------------  
955046621744201729  cz_haiwai_ldq_mysql_to_ck  RUNNING     2025-03-20 18:14:22.731  
我把这个Seatunnel任务停止后

![Image](https://github.com/user-attachments/assets/1e198b48-f7c2-4ccc-9ca7-e477da86317e)
apache/dolphinscheduler-worker:3.1.9里面的Seatunnel任务并没有停止，还是在进行运行。
Job ID              Job Name                   Job Status  Submit Time              Finished Time            
------------------  -------------------------  ----------  -----------------------  -----------------------  
955046621744201729  cz_haiwai_ldq_mysql_to_ck  RUNNING     2025-03-20 18:14:22.731

**Comment by wanshicheng** [comment]
我认为在cluster模式下应该使用seatunnel的rest api去彻底解决这个问题！

**Comment by pzc-hhh** [comment]
At the moment i don't use seatunnel and ds anymore



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 6, 2025 17:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-worker] Unableto stop tasks in Seatunnel cluster (Issue #15738)


wanshicheng left a comment (apache/dolphinscheduler#15738)
 
我认为应该使用seatunnel的rest api去彻底解决这个问题！

**Comment by wolfewf** [comment]
所以这个问题是解决还是没有解决？

**Comment by 13813586515** [comment]
> 所以这个问题是解决还是没有解决？

显然并没有，ds只是将ds自己的task关闭了，但是st的人物依然没有关闭

**Comment by cqutwangyu** [comment]
> 我认为在cluster模式下应该使用seatunnel的rest api去彻底解决这个问题！

这个是正确的方式，因为一些原因我目前没有再使用DS，但我开发的产品，在管理ST任务时，通过rest api的方式能够完美解决。

**Comment by wolfewf** [comment]
@cqutwangyu 
请问下ds怎么调用到seatunnel 的cluster

**Comment by pzc-hhh** [comment]
ds设置cluster模式，seatunnel也也要部署集群模式。



---Original---
From: ***@***.***&gt;
Date: Sat, Aug 16, 2025 16:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-worker] Unableto stop tasks in Seatunnel cluster (Issue #15738)


wolfewf left a comment (apache/dolphinscheduler#15738)
 
请问下ds怎么调用到seatunnel 的cluster

**Comment by dawner84** [comment]
same issue, please fix it.

**Comment by davidzollo** [comment]
Which version do you use? As far as I know, this issue has been solved in 3.3.x version

**Comment by dawner84** [comment]
> Which version do you use? As far as I know, this issue has been solved in 3.3.x version

  i am using apache-dolphinscheduler-3.3.2-bin.tar.gz now , look like still not working . 
  i saw the code in "cancelApplication.ProcessUtils.kill" it only use kill to stop the seatnunnel process which is not working for seatunnel cluster mode,   i only can cancel it manaully via command "./bin/seatunnel.sh -can 1039202262053814273" .
  for local mode ,it  the process look like still not kill success ,i am still checking .

**Comment by dawner84** [comment]
> > Which version do you use? As far as I know, this issue has been solved in 3.3.x version
> 
> i am using apache-dolphinscheduler-3.3.2-bin.tar.gz now , look like still not working . i saw the code in "cancelApplication.ProcessUtils.kill" it only use kill to stop the seatnunnel process which is not working for seatunnel cluster mode, i only can cancel it manaully via command "./bin/seatunnel.sh -can 1039202262053814273" . for local mode ,it the process look like still not kill success ,i am still checking .

i found the reasonin local mode its because JDK throw a "unnamed module" error in logs , i changed the JDK version to 1.8 , it works as expect. .

how about cluster mode ? any plan to support it ?

**Comment by pzc-hhh** [comment]
The source code needs to be modified, specifically the part related to Seatunnel tasks. Please modify the method for canceling tasks.



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 22, 2025 16:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-worker] Unableto stop tasks in Seatunnel cluster (Issue #15738)


dawner84 left a comment (apache/dolphinscheduler#15738)
   
Which version do you use? As far as I know, this issue has been solved in 3.3.x version
  
i am using apache-dolphinscheduler-3.3.2-bin.tar.gz now , look like still not working . i saw the code in "cancelApplication.ProcessUtils.kill" it only use kill to stop the seatnunnel process which is not working for seatunnel cluster mode, i only can cancel it manaully via command "./bin/seatunnel.sh -can 1039202262053814273" . for local mode ,it the process look like still not kill success ,i am still checking .
  
i found the reasonin local mode its because JDK throw a "unnamed module" error in logs , i changed the JDK version to 1.8 , it works as expect. .
 
how about cluster mode ? any plan to support it ?
