### ISSUE TITLE
[Feature][doc] Update readme screenshot and description

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#9897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/apache/dolphinscheduler/blob/dev/README.md
https://github.com/apache/dolphinscheduler/blob/dev/README_zh_CN.md

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jj551** [comment]
Hi,brother Zhong @zhongjiajie ,has been resolved？

**Comment by zhongjiajie** [comment]
Hi, @Kodalien , screenshot was already updated by #9970 . But description still do not updated

**Comment by jj551** [comment]
> Hi, @Kodalien , screenshot was already updated by #9970 . But description still do not updated

@zhongjiajie  Q:( description ? give a hint

**Comment by zhongjiajie** [comment]
our description is a bit verbose, maybe we should reduce them to some keywords.
<img width="888" alt="image" src="https://user-images.githubusercontent.com/15820530/168507679-df77233c-ab9f-4118-ac5d-567ca1ee15a5.png">
